spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/groceryappdb
    username: root
    password: root
  jpa:
    database: POSTGRESQL
    hibernate.ddl-auto: update
    show-sql: true